# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: java -jar target/mymaven-1.0-SNAPSHOT.jar
  displayName: 'Running'
